version: '3'

services:
  app:
    container_name: misis-hack-app
    build:
      context: .
    depends_on:
      - db
    networks:
      - misis-hack_network
    ports:
      - 3000:3000
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
  db:
    image: postgres:latest
    container_name: misis-hack-db
    networks:
      - misis-hack_network
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped

networks:
  misis-hack_network:
